src = ["resources"]
exclude = ["venv*", "unit_tests"]
line-length = 120
respect-gitignore = true

[lint]
select = [
#     "F",  # pyflakes
#    "E", "W",  # Pycodestyle
#    "I001", # isort
    "D",  # docstring checker
]