# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0

name: Check code quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ruff_lint:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Code style
        run: ruff check

  license_check:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: License check
        run: reuse lint

  rf_style_check:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: RobotFramework style check
        run: robocop check
    # We haven't settled on a style for RobotFramework yet, enforce check when consensus is reached
    continue-on-error: true

  spelling_check:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Spelling checker
        run: codespell . --check-filenames --skip *.html,*.pem,*.xml,*venv*,*fips/*.py

  pylint:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pylint check
        run: pylint --fail-under=9.4 resources

  unit_test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
      env:
        OQS_INSTALL_PATH: "/root/_oqs"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Unit tests
        run: PYTHONPATH=./resources python3 -m unittest discover -s unit_tests

  # type_check:
  #   runs-on: ubuntu-22.04
  #   container:
  #     image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Pyright check
  #       run: PYTHONPATH=./resources pyright ./resources