name: Check code quality

on:
  push:
    branches:
      - main
      - pq_migration2
  pull_request:
    branches:
      - main
      - pq_migration2
  workflow_dispatch:

jobs:
  check_code_quality:
    runs-on: ubuntu-22.04
    # The steps are allowed to continue on error, so that we provide as
    # much feedback at once as possible. Nevertheless, this job must fail in
    # the end if there was at least one error.
    continue-on-error: true
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Code style
        run: ruff check

      - name: License check
        run: reuse lint

      - name: RobotFramework style check
        run: robocop --report rules_by_error_type

      - name: Spelling checker
        run: codespell . --check-filenames --skip *.html,*.pem,*.xml,*venv*,*fips/*.py

      - name: Pylint check
        run: pylint --fail-under=9.38 resources

      - name: Unit tests
        run: PYTHONPATH=./resources python3 -m unittest discover -s unit_tests

      - name: Pyright check
        run: |
          export ERRORS=$(PYTHONPATH=./resources pyright ./resources | tail -n 1 | grep -o '^[0-9]*')
          [ -z "$ERRORS" ] && ERRORS=0  # Set ERRORS to 0 if it is empty
          [ "$ERRORS" -lt 85 ] 2>/dev/null && echo "Success." || (echo "Failure. Error count:" && exit 1)
